# Generated by Django 4.0.6 on 2024-12-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caudais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicao',
            name='valor',
            field=models.FloatField(),
        ),
    ]
