# Generated by Django 4.0.6 on 2024-12-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caudais', '0002_alter_medicao_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicao',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
