# Generated by Django 4.0.6 on 2024-12-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caudais', '0003_alter_medicao_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicao',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
