# Generated by Django 4.0.6 on 2025-02-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caudais', '0004_alter_medicao_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicao',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
