# Generated by Django 5.1.3 on 2025-04-18 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caudais', '0005_alter_medicao_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicaoProcessada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('normalized', 'Normalizado'), ('jq', 'Reconstruído (JQ)'), ('tbats', 'Reconstruído (TBATS)')], max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('valor', models.FloatField()),
                ('ano', models.IntegerField()),
                ('ponto_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes_processadas', to='caudais.pontomedida')),
            ],
            options={
                'unique_together': {('ponto_medida', 'metodo', 'timestamp')},
            },
        ),
    ]
