# Generated by Django 5.1.3 on 2025-04-19 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caudais', '0006_medicaoprocessada'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatisticaAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('normalized', 'Normalizado'), ('jq', 'Reconstruído (JQ)'), ('tbats', 'Reconstruído (TBATS)'), ('raw', 'Raw')], max_length=20)),
                ('ano', models.IntegerField()),
                ('total', models.FloatField()),
                ('media', models.FloatField()),
                ('contagem', models.IntegerField()),
                ('ponto_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caudais.pontomedida')),
            ],
            options={
                'unique_together': {('ponto_medida', 'metodo', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='EstatisticaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('normalized', 'Normalizado'), ('jq', 'Reconstruído (JQ)'), ('tbats', 'Reconstruído (TBATS)'), ('raw', 'Raw')], max_length=20)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('total', models.FloatField()),
                ('media', models.FloatField()),
                ('contagem', models.IntegerField()),
                ('ponto_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caudais.pontomedida')),
            ],
            options={
                'unique_together': {('ponto_medida', 'metodo', 'ano', 'mes')},
            },
        ),
    ]
