# Generated by Django 4.0.6 on 2024-04-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Praias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='praia',
        ),
        migrations.AddField(
            model_name='servico',
            name='praia',
            field=models.ManyToManyField(blank=True, related_name='servicos', to='Praias.praia'),
        ),
    ]
