# Generated by Django 4.0.6 on 2024-04-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Praias', '0002_remove_servico_praia_servico_praia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='praia',
        ),
        migrations.AddField(
            model_name='praia',
            name='servicos',
            field=models.ManyToManyField(blank=True, related_name='praias', to='Praias.servico'),
        ),
    ]
