# Generated by Django 4.0.6 on 2024-06-05 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacientifica',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areasCientificas', to='curso.curso'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='linguagens',
            field=models.ManyToManyField(related_name='disciplinas', to='curso.linguagemprogramacao'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='curso.disciplina'),
        ),
    ]
