# Generated by Django 4.0.6 on 2024-06-09 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_areacientifica_curso_disciplina_linguagens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='curso.curso'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='linguagens',
            field=models.ManyToManyField(blank=True, null=True, related_name='disciplinas', to='curso.linguagemprogramacao'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linguagensProgramacao',
            field=models.ManyToManyField(blank=True, null=True, related_name='projetos', to='curso.linguagemprogramacao'),
        ),
    ]
