# Generated by Django 4.0.6 on 2024-06-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_remove_disciplina_curso_disciplina_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ManyToManyField(blank=True, null=True, related_name='disciplinas', to='curso.curso'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='linguagens',
            field=models.ManyToManyField(blank=True, null=True, related_name='disciplinas', to='curso.linguagemprogramacao'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linguagensProgramacao',
            field=models.ManyToManyField(blank=True, null=True, related_name='projetos', to='curso.linguagemprogramacao'),
        ),
    ]
