# Generated by Django 4.0.6 on 2024-06-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_alter_disciplina_curso_alter_disciplina_linguagens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(null=True, upload_to='curso/fotosProjetos'),
        ),
    ]
