# Generated by Django 4.0.6 on 2024-06-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_alter_projeto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='curso/fotosProjetos'),
        ),
    ]
