# Generated by Django 4.0.6 on 2024-04-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='ano_lancamento',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='banda',
            name='ano_criacao',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='banda',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='duracao',
            field=models.DurationField(null=True),
        ),
    ]
