# Generated by Django 4.0.6 on 2024-04-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_album_ano_lancamento_banda_ano_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='bandas/fotosAlbums'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='bandas/fotosBandas'),
        ),
    ]
