# Generated by Django 4.0.6 on 2024-04-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_alter_album_capa_alter_banda_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='titulo_Album',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='banda',
            name='nome_banda',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='musica',
            name='nome_musica',
            field=models.CharField(max_length=50),
        ),
    ]
